#!/bin/env bash

if [ ! "$(grep WINEPREFIX env.sh)" ]; then
  printf "export WINEPREFIX=$(pwd)/wine" >> env.sh
fi

source env.sh

ln -sf setup_*/setup*.exe .

[ -d wine] && tra wine
winetricks -q dotnet46
wine setup*.exe

# GUI installer will launch
# Go through install process, then exit

ls wine/drive_c/Program\ Files/BrightSign
