#!/bin/env bash

if [ ! "$(grep WINEPREFIX env.sh)" ]; then
  printf "export WINEPREFIX=$(pwd)/wine" >> env.sh
fi

source env.sh

ln -sf setup_*/setup*.exe .

[ -d wine ] && rm -rf wine

if ! winetricks -q dotnet46; then
  exit 1
fi

wine setup*.exe

# GUI installer will launch
# Go through the install process until it completes, then exit

rm setup*.exe
